CREATE SCHEMA silver;
CREATE SCHEMA gold;

CREATE TABLE silver.temp_incidents (
    incident_number BIGINT,
    exposure_number INT,
    id INTEGER PRIMARY KEY,
    address TEXT,
    incident_date DATE,
    call_number BIGINT,
    alarm_dttm TIMESTAMP,
    arrival_dttm TIMESTAMP,
    close_dttm TIMESTAMP,
    city VARCHAR(100),
    zipcode VARCHAR(100),
    battalion VARCHAR(100),
    station_area VARCHAR(100),
    suppression_units INT,
    suppression_personnel INT,
    ems_units INT,
    ems_personnel INT,
    other_units INT,
    other_personnel INT,
    first_unit_on_scene VARCHAR(50),
    fire_fatalities INT,
    fire_injuries INT,
    civilian_fatalities INT,
    civilian_injuries INT,
    number_of_alarms INT,
    primary_situation TEXT,
    mutual_aid VARCHAR(100),
    action_taken_primary TEXT,
    property_use TEXT,
    supervisor_district VARCHAR(100),
    neighborhood_district TEXT,
    point TEXT,
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP
);

CREATE TABLE silver.incidents (
    incident_number BIGINT,
    exposure_number INT,
    id INTEGER PRIMARY KEY,
    address TEXT,
    incident_date DATE,
    call_number BIGINT,
    alarm_dttm TIMESTAMP,
    arrival_dttm TIMESTAMP,
    close_dttm TIMESTAMP,
    city VARCHAR(100),
    zipcode VARCHAR(100),
    battalion VARCHAR(100),
    station_area VARCHAR(100),
    suppression_units INT,
    suppression_personnel INT,
    ems_units INT,
    ems_personnel INT,
    other_units INT,
    other_personnel INT,
    first_unit_on_scene VARCHAR(50),
    fire_fatalities INT,
    fire_injuries INT,
    civilian_fatalities INT,
    civilian_injuries INT,
    number_of_alarms INT,
    primary_situation TEXT,
    mutual_aid VARCHAR(100),
    action_taken_primary TEXT,
    property_use TEXT,
    supervisor_district VARCHAR(100),
    neighborhood_district TEXT,
    point TEXT,
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP,
    updated_at TIMESTAMP
);
